language: ruby
rvm:
  - ruby-2.1.4
  - ruby-2.0.0
  - ruby-1.9.3
  - rbx
matrix:
  include:
    - rvm: ruby-2.1.2-clang
      env: CXX=clang++
    - rvm: ruby-head
    - rvm: ruby-head-clang
      env: CXX=clang++
    - rvm: ree
    - rvm: ruby-1.8.7
  allow_failures:
    - rvm: ree
    - rvm: ruby-1.8.7
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
bundler_args: --jobs=1 --retry=3
script:
  - MAKEFLAGS+=-j8 bundle exec rake spec build binary --trace
  - MAKEFLAGS+=-j8 travis_wait gem install pkg/*.gem
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
cache: bundler
