rvm:
  - 2.0.0
  - 2.1.2
  - 1.9.3
  - rbx-2
  - ree
matrix:
  allow_failures:
    - rvm: ree
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
before_install:
  - sudo apt-get update