language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2
  - ree
matrix:
  allow_failures:
    - rvm: ree
    - rvm: 1.8.7
  include:
    - rvm: 2.1.2-clang
      env: CXX=clang++
  fast_finish: true
bundler_args: -j4
script:
  - bundle exec rake spec build binary --trace
  - travis_wait gem install pkg/*.gem
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
cache: bundler