language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2
  - ree
env:
  - CXX=g++
  - CXX=clang++
matrix:
  allow_failures:
    - rvm: ree
    - rvm: 1.8.7
bundler_args: -j4
script:
  - travis_wait bundle exec rake
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
cache: bundler